kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: open-ecosystem-challenge
nodes:
- role: control-plane
  # Just add all port mappings that might be necessary for a challenge
  extraPortMappings:
    # ArgoCD
  - hostPort: 30100
    containerPort: 30100
    protocol: TCP